{%set name = "mccabe" %}
{%set version = "0.5.3" %}
{%set hash_type = "sha256" %}
{%set hash_val = "16293af41e7242031afd73896fef6458f4cad38201d21e28f344fff50ae1c25e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/PyCQA/mccabe
  license: MIT
  summary: 'McCabe complexity checker for Python'

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - ocefpaf
